//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.weispa.Web.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBaseInfoService")]
    public interface IBaseInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/GetProvince", ReplyAction="http://tempuri.org/IBaseInfoService/GetProvinceResponse")]
        string GetProvince(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/GetCity", ReplyAction="http://tempuri.org/IBaseInfoService/GetCityResponse")]
        string GetCity(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/GetSeries", ReplyAction="http://tempuri.org/IBaseInfoService/GetSeriesResponse")]
        string GetSeries(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/GetModel", ReplyAction="http://tempuri.org/IBaseInfoService/GetModelResponse")]
        string GetModel(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/GetFriendlyLink", ReplyAction="http://tempuri.org/IBaseInfoService/GetFriendlyLinkResponse")]
        string GetFriendlyLink(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/GetLogNote", ReplyAction="http://tempuri.org/IBaseInfoService/GetLogNoteResponse")]
        string GetLogNote(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/GetSalesConsultant", ReplyAction="http://tempuri.org/IBaseInfoService/GetSalesConsultantResponse")]
        string GetSalesConsultant(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/GetDealer", ReplyAction="http://tempuri.org/IBaseInfoService/GetDealerResponse")]
        string GetDealer(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/GetDealerImage", ReplyAction="http://tempuri.org/IBaseInfoService/GetDealerImageResponse")]
        string GetDealerImage(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/GetNews", ReplyAction="http://tempuri.org/IBaseInfoService/GetNewsResponse")]
        string GetNews(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/SendOnlineQuestion", ReplyAction="http://tempuri.org/IBaseInfoService/SendOnlineQuestionResponse")]
        string SendOnlineQuestion(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/GetOnlineAnswer", ReplyAction="http://tempuri.org/IBaseInfoService/GetOnlineAnswerResponse")]
        string GetOnlineAnswer(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/SendLeads", ReplyAction="http://tempuri.org/IBaseInfoService/SendLeadsResponse")]
        string SendLeads(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/GetFeedBackLeads", ReplyAction="http://tempuri.org/IBaseInfoService/GetFeedBackLeadsResponse")]
        string GetFeedBackLeads(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/GetCarsPrice", ReplyAction="http://tempuri.org/IBaseInfoService/GetCarsPriceResponse")]
        string GetCarsPrice(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/GetPushList", ReplyAction="http://tempuri.org/IBaseInfoService/GetPushListResponse")]
        string GetPushList(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/GetAdvertisement", ReplyAction="http://tempuri.org/IBaseInfoService/GetAdvertisementResponse")]
        string GetAdvertisement(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/GetPromotion", ReplyAction="http://tempuri.org/IBaseInfoService/GetPromotionResponse")]
        string GetPromotion(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/SendCallRecord", ReplyAction="http://tempuri.org/IBaseInfoService/SendCallRecordResponse")]
        string SendCallRecord(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/SendSalesClueIdentity", ReplyAction="http://tempuri.org/IBaseInfoService/SendSalesClueIdentityResponse")]
        string SendSalesClueIdentity(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/SyncSaleClues", ReplyAction="http://tempuri.org/IBaseInfoService/SyncSaleCluesResponse")]
        string SyncSaleClues(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/SyncNews", ReplyAction="http://tempuri.org/IBaseInfoService/SyncNewsResponse")]
        string SyncNews(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/SyncOnlineQAs", ReplyAction="http://tempuri.org/IBaseInfoService/SyncOnlineQAsResponse")]
        string SyncOnlineQAs(string inputParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseInfoService/SyncOperationLogs", ReplyAction="http://tempuri.org/IBaseInfoService/SyncOperationLogsResponse")]
        string SyncOperationLogs(string inputParam);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBaseInfoServiceChannel : com.weispa.Web.ServiceReference1.IBaseInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BaseInfoServiceClient : System.ServiceModel.ClientBase<com.weispa.Web.ServiceReference1.IBaseInfoService>, com.weispa.Web.ServiceReference1.IBaseInfoService {
        
        public BaseInfoServiceClient() {
        }
        
        public BaseInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaseInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaseInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaseInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetProvince(string inputParam) {
            return base.Channel.GetProvince(inputParam);
        }
        
        public string GetCity(string inputParam) {
            return base.Channel.GetCity(inputParam);
        }
        
        public string GetSeries(string inputParam) {
            return base.Channel.GetSeries(inputParam);
        }
        
        public string GetModel(string inputParam) {
            return base.Channel.GetModel(inputParam);
        }
        
        public string GetFriendlyLink(string inputParam) {
            return base.Channel.GetFriendlyLink(inputParam);
        }
        
        public string GetLogNote(string inputParam) {
            return base.Channel.GetLogNote(inputParam);
        }
        
        public string GetSalesConsultant(string inputParam) {
            return base.Channel.GetSalesConsultant(inputParam);
        }
        
        public string GetDealer(string inputParam) {
            return base.Channel.GetDealer(inputParam);
        }
        
        public string GetDealerImage(string inputParam) {
            return base.Channel.GetDealerImage(inputParam);
        }
        
        public string GetNews(string inputParam) {
            return base.Channel.GetNews(inputParam);
        }
        
        public string SendOnlineQuestion(string inputParam) {
            return base.Channel.SendOnlineQuestion(inputParam);
        }
        
        public string GetOnlineAnswer(string inputParam) {
            return base.Channel.GetOnlineAnswer(inputParam);
        }
        
        public string SendLeads(string inputParam) {
            return base.Channel.SendLeads(inputParam);
        }
        
        public string GetFeedBackLeads(string inputParam) {
            return base.Channel.GetFeedBackLeads(inputParam);
        }
        
        public string GetCarsPrice(string inputParam) {
            return base.Channel.GetCarsPrice(inputParam);
        }
        
        public string GetPushList(string inputParam) {
            return base.Channel.GetPushList(inputParam);
        }
        
        public string GetAdvertisement(string inputParam) {
            return base.Channel.GetAdvertisement(inputParam);
        }
        
        public string GetPromotion(string inputParam) {
            return base.Channel.GetPromotion(inputParam);
        }
        
        public string SendCallRecord(string inputParam) {
            return base.Channel.SendCallRecord(inputParam);
        }
        
        public string SendSalesClueIdentity(string inputParam) {
            return base.Channel.SendSalesClueIdentity(inputParam);
        }
        
        public string SyncSaleClues(string inputParam) {
            return base.Channel.SyncSaleClues(inputParam);
        }
        
        public string SyncNews(string inputParam) {
            return base.Channel.SyncNews(inputParam);
        }
        
        public string SyncOnlineQAs(string inputParam) {
            return base.Channel.SyncOnlineQAs(inputParam);
        }
        
        public string SyncOperationLogs(string inputParam) {
            return base.Channel.SyncOperationLogs(inputParam);
        }
    }
}
